import Head from 'next/head'
import styles from '@/styles/home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Watermak</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Watermark</h1>
        <form action="" className={styles.photos_form}>
          <input type="text" name='watermark-text' placeholder="write your watermark here" />
          <input type="file" name="photo" id="photo" />
          <button>Upload</button>
        </form>
      </main>
    </>
  )
}
